language: java
deploy:
  api-key:
    secure: df/NtvINd2g6o8E+XRQsy5fIoGknXSju2S2zAZPGf5CKlc3JIs5/GrwOGumvhLiccRvFpLaArNJXLQILge5FY6ELkGsnDuu4Jk6dD3qCzkyk9IZYo7i7K+SHH025kaHG27vsljpwWaSI3jMR6+cPfdiD50UcemmA7zteCpIA14cIFRMEHT9Ofxz6lhetlYTdeyyGk7AIy82BqU/zfM0runSK3AVdBPdksKQsnH2QPWxbeLBTKPFb0rrWKIc9UYG6bwLTj+t9pXRseCZvMxsYy6m1QA6EfddrJZdM4OVWV3pd9jl+nIk/iWYuxQn1kDusLSWFgUYd4soGpnpES2kGC91/VvQVA/OEfSY+PbWuED+qo+5xebe0uUamLr3jLPFVC8Cnx0r84bAGV5Fr80SJDx2QYIEdYgE2nySEylobIjRaLr0wZqOzZbXREF7KQzTHqss1H3NYS7KLMn/A8eyR4jnitFf3KLn2KLIQcEmR0P8cPHxC2F4zYEINZadxWLQ63Xp0BmMqwkCYM0PthBytCSxyxRP0bRPRSTj6+lnj0LfpbayS6j863zSoQ8mDmftGADeFeiu2xHiOEAwpPun464xOhwqwvSpfoR7QJxVY6wNRc59mOPGB/o3Aofl5BQk7svWWs8GFvoBcBMlyTvBbTwTe3puHtL/jRYC62288J2s=
  provider: heroku
  app:
    staging: lgm-trilharest-filmes-staging
    master: lgm-trilharest-filmes-producti